### PR TITLE
Make channel, prefix, and gateway configurable

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I'll rebase on top of #16

**Comment by whyrusleeping** [comment]
cool, i merged #16 let me know when you got the rebase done

**Comment by ghost** [comment]
it's already done :)

**Comment by whyrusleeping** [comment]
but my commit from #16 is also part of this PR? thats weird

**Comment by ghost** [comment]
Yeah not sure, it was the same commit, github should have handled that. I rebased on master again including the merge commit and it looks good now

**Comment by whyrusleeping** [comment]
cool, LGTM

**Pull request merged**
